import { veterinariasIniciales } from "./veterinarias-data.js?v=20260804-4";

const state={all:veterinariasIniciales,filter:"todos"};const grid=document.getElementById("grid"),search=document.getElementById("search"),results=document.getElementById("results"),filters=document.getElementById("filters");
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const digits=v=>String(v||"").replace(/\D/g,"");const wa=v=>{let n=digits(v);if(!n)return"";if(n.startsWith("0"))n=n.slice(1);if(!n.startsWith("54"))n=`549${n}`;return n};
const rank=v=>v.urgencias24hs?0:1;
function detail(icon,label,value){return value?`<p class="detail">${icon} <strong>${label}:</strong> ${esc(value)}</p>`:""}
function card(v){const phone=digits(v.telefonoPrincipal),whatsapp=wa(v.whatsappPrincipal),address=(v.direccion||"").trim();return `<article class="card"><div class="badges">${v.urgencias24hs?'<span class="badge urgent">Urgencias 24 hs</span>':""}</div><h2>${esc(v.nombre)}</h2>${detail("📍","Dirección",address)}${detail("📞","Teléfono",v.telefonoPrincipal)}${detail("📞","Teléfono alternativo",v.telefonoSecundario)}${detail("🕒","Horarios",v.horarios)}${detail("🐾","Atención",v.tipoAtencion)}${v.urgencias24hs?`<div class="notice">${detail("🚨","Urgencias 24 hs",`${v.contactoUrgenciasNombre||v.nombre}${v.telefonoUrgencias?` — ${v.telefonoUrgencias}`:""}`)}</div>`:""}${v.observaciones?`<p class="observations">${esc(v.observaciones)}</p>`:""}<div class="actions">${phone?`<a class="btn" href="tel:+${phone}">📞 Llamar</a>`:""}${whatsapp?`<a class="btn whatsapp" href="https://wa.me/${whatsapp}" target="_blank" rel="noopener">WhatsApp</a>`:""}${address&&!address.toLowerCase().startsWith("asociado")?`<a class="btn map" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${address}, Saladillo, Buenos Aires`)}" target="_blank" rel="noopener">📍 Ver ubicación</a>`:""}</div></article>`}
function apply(){const q=search.value.toLocaleLowerCase("es").trim();let items=state.all.filter(v=>v.visible!==false);if(q)items=items.filter(v=>`${v.nombre} ${v.direccion} ${v.tipoAtencion}`.toLocaleLowerCase("es").includes(q));if(state.filter==="urgencias")items=items.filter(v=>v.urgencias24hs);else if(state.filter!=="todos")items=items.filter(v=>(v.tipoAtencion||"").toLocaleLowerCase("es").includes(state.filter));items.sort((a,b)=>rank(a)-rank(b)||(a.orden??999)-(b.orden??999)||(a.nombre||"").localeCompare(b.nombre||"","es"));results.textContent=`${items.length} contacto${items.length===1?"":"s"}`;grid.innerHTML=items.length?items.map(card).join(""):'<div class="empty">No encontramos contactos con esos filtros.</div>'}
search.addEventListener("input",apply);filters.addEventListener("click",e=>{const b=e.target.closest("button[data-filter]");if(!b)return;state.filter=b.dataset.filter;filters.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));apply()});
apply();
