import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getFirestore, collection, addDoc, doc, getDocs, setDoc, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
import { veterinariasIniciales } from "./veterinarias-data.js";

const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app);const form=document.getElementById("form"),list=document.getElementById("list"),adminSearch=document.getElementById("adminSearch"),formMsg=document.getElementById("formMsg"),listMsg=document.getElementById("listMsg"),save=document.getElementById("save");const state={all:[]};
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function reset(){form.reset();form.elements.documentId.value="";form.elements.visible.checked=true;form.elements.orden.value=999;document.getElementById("formTitle").textContent="Nueva ficha";formMsg.textContent=""}
function payload(){const d=Object.fromEntries(new FormData(form));return {nombre:d.nombre.trim(),direccion:d.direccion.trim(),telefonoPrincipal:d.telefonoPrincipal.trim(),telefonoSecundario:d.telefonoSecundario.trim(),whatsappPrincipal:d.whatsappPrincipal.trim(),whatsappSecundario:d.whatsappSecundario.trim(),horarios:d.horarios.trim(),tipoAtencion:d.tipoAtencion.trim(),urgencias24hs:form.elements.urgencias24hs.checked,contactoUrgenciasNombre:d.contactoUrgenciasNombre.trim(),telefonoUrgencias:d.telefonoUrgencias.trim(),whatsappUrgencias:d.whatsappUrgencias.trim(),observaciones:d.observaciones.trim(),estado:d.estado,visible:form.elements.visible.checked,orden:Number(d.orden)||999,ultimaActualizacion:serverTimestamp()}}
function render(){const q=adminSearch.value.toLowerCase().trim(),items=state.all.filter(v=>!q||`${v.nombre} ${v.telefonoPrincipal} ${v.direccion}`.toLowerCase().includes(q));list.innerHTML=items.length?items.map(v=>`<article class="admin-item"><strong>${esc(v.nombre)}</strong> ${v.visible===false?'<span class="badge pending">Oculta</span>':""}${v.urgencias24hs?'<span class="badge urgent">Urgencias 24 hs</span>':""}<p>${esc(v.direccion||"Dirección a confirmar")} · ${esc(v.telefonoPrincipal||"Sin teléfono")}</p><p>Estado: ${esc(v.estado||"a_confirmar")} · ID exacto: <code>${esc(v.documentId)}</code></p><div class="admin-actions"><button data-action="edit" data-id="${esc(v.documentId)}">Editar</button><button class="secondary" data-action="toggle" data-id="${esc(v.documentId)}">${v.visible===false?"Mostrar":"Ocultar"}</button><button class="danger" data-action="delete" data-id="${esc(v.documentId)}">Eliminar ficha</button></div></article>`).join(""):"<p>No hay fichas para mostrar.</p>"}
async function load(){const snap=await getDocs(collection(db,"veterinarias"));state.all=snap.docs.map(d=>({documentId:d.id,...d.data()})).filter(v=>!v.eliminado).sort((a,b)=>(a.orden??999)-(b.orden??999));render();listMsg.textContent=`${state.all.length} fichas cargadas.`}
form.addEventListener("submit",async e=>{e.preventDefault();save.disabled=true;formMsg.textContent="Guardando…";try{const id=form.elements.documentId.value;if(id)await updateDoc(doc(db,"veterinarias",id),payload());else await addDoc(collection(db,"veterinarias"),{...payload(),creadoEn:serverTimestamp()});formMsg.textContent="Ficha guardada correctamente.";reset();await load()}catch(err){console.error(err);formMsg.textContent=`No se pudo guardar: ${err.message||err}`}finally{save.disabled=false}});
list.addEventListener("click",async e=>{const b=e.target.closest("button[data-action]");if(!b)return;const item=state.all.find(v=>v.documentId===b.dataset.id);if(!item)return;if(b.dataset.action==="edit"){["documentId","nombre","direccion","telefonoPrincipal","telefonoSecundario","whatsappPrincipal","whatsappSecundario","horarios","tipoAtencion","contactoUrgenciasNombre","telefonoUrgencias","whatsappUrgencias","observaciones","estado","orden"].forEach(k=>{if(form.elements[k])form.elements[k].value=item[k]??""});form.elements.urgencias24hs.checked=Boolean(item.urgencias24hs);form.elements.visible.checked=item.visible!==false;document.getElementById("formTitle").textContent=`Editar: ${item.nombre}`;scrollTo({top:0,behavior:"smooth"});return}try{b.disabled=true;if(b.dataset.action==="toggle")await updateDoc(doc(db,"veterinarias",item.documentId),{visible:item.visible===false,ultimaActualizacion:serverTimestamp()});if(b.dataset.action==="delete"){if(!confirm(`¿Eliminar lógicamente la ficha con ID exacto?\n\n${item.documentId}\n\nNo se borrará físicamente.`))return;await updateDoc(doc(db,"veterinarias",item.documentId),{eliminado:true,eliminadoEn:serverTimestamp(),visible:false})}await load()}catch(err){console.error(err);listMsg.textContent=`No se pudo actualizar: ${err.message||err}`}finally{b.disabled=false}});
document.getElementById("cancel").addEventListener("click",reset);adminSearch.addEventListener("input",render);document.getElementById("seed").addEventListener("click",async e=>{if(!confirm("¿Cargar los 15 datos iniciales? Solo se crearán IDs que todavía no existan."))return;const b=e.currentTarget;b.disabled=true;listMsg.textContent="Cargando datos iniciales…";try{const snap=await getDocs(collection(db,"veterinarias")),existing=new Set(snap.docs.map(d=>d.id));for(const v of veterinariasIniciales){if(existing.has(v.id))continue;const {id,...data}=v;await setDoc(doc(db,"veterinarias",id),{...data,creadoEn:serverTimestamp(),ultimaActualizacion:serverTimestamp()})}await load();listMsg.textContent="Datos iniciales disponibles. No se duplicaron fichas existentes."}catch(err){console.error(err);listMsg.textContent=`No se pudieron cargar: ${err.message||err}`}finally{b.disabled=false}});load().catch(err=>{console.error(err);listMsg.textContent="No se pudo conectar con Firestore. Revisá la configuración y los permisos."});
